---
# ============================================
# SonarQube Deployment with Ansible
# ============================================
- name: Deploy SonarQube to Kubernetes
  hosts: localhost
  connection: local
  become: no

  vars:
    namespace: jenkins
    sonarqube_version: "lts-community"  # Long-term support community edition

  tasks:
    - name: Create SonarQube PersistentVolumeClaim
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: sonarqube-data
            namespace: "{{ namespace }}"
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi

    - name: Deploy SonarQube
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: sonarqube
            namespace: "{{ namespace }}"
            labels:
              app: sonarqube
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: sonarqube
            template:
              metadata:
                labels:
                  app: sonarqube
              spec:
                containers:
                  - name: sonarqube
                    image: "sonarqube:{{ sonarqube_version }}"
                    ports:
                      - containerPort: 9000
                        name: http
                    env:
                      - name: SONAR_ES_BOOTSTRAP_CHECKS_DISABLE
                        value: "true"
                      - name: SONAR_JDBC_URL
                        value: "jdbc:h2:mem:sonarqube"  # In-memory H2 for demo
                    volumeMounts:
                      - name: sonarqube-data
                        mountPath: /opt/sonarqube/data
                      - name: sonarqube-extensions
                        mountPath: /opt/sonarqube/extensions
                      - name: sonarqube-logs
                        mountPath: /opt/sonarqube/logs
                    resources:
                      requests:
                        memory: "1Gi"
                        cpu: "500m"
                      limits:
                        memory: "2Gi"
                        cpu: "1000m"
                    livenessProbe:
                      httpGet:
                        path: /api/system/status
                        port: 9000
                      initialDelaySeconds: 60
                      periodSeconds: 30
                      timeoutSeconds: 5
                    readinessProbe:
                      httpGet:
                        path: /api/system/status
                        port: 9000
                      initialDelaySeconds: 60
                      periodSeconds: 10
                      timeoutSeconds: 5
                volumes:
                  - name: sonarqube-data
                    persistentVolumeClaim:
                      claimName: sonarqube-data
                  - name: sonarqube-extensions
                    emptyDir: {}
                  - name: sonarqube-logs
                    emptyDir: {}

    - name: Create SonarQube Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: sonarqube
            namespace: "{{ namespace }}"
            labels:
              app: sonarqube
          spec:
            type: NodePort
            ports:
              - port: 9000
                targetPort: 9000
                nodePort: 30900
                protocol: TCP
                name: http
            selector:
              app: sonarqube

    - name: Wait for SonarQube to be ready
      kubernetes.core.k8s_info:
        kind: Deployment
        namespace: "{{ namespace }}"
        name: sonarqube
        wait: yes
        wait_condition:
          type: Available
          status: "True"
        wait_timeout: 300

    - name: Get SonarQube NodePort
      kubernetes.core.k8s_info:
        kind: Service
        namespace: "{{ namespace }}"
        name: sonarqube
      register: sonarqube_service

    - name: Display SonarQube Access Information
      debug:
        msg:
          - "âœ… SonarQube deployed successfully!"
          - "ðŸŒ Access URL: http://localhost:30900"
          - "ðŸ‘¤ Default credentials:"
          - "   Username: admin"
          - "   Password: admin (you'll be asked to change it on first login)"
          - ""
          - "ðŸ“‹ Next steps:"
          - "1. Access SonarQube at http://localhost:30900"
          - "2. Login with admin/admin"
          - "3. Create a new token: User > My Account > Security > Generate Token"
          - "4. Configure SonarQube server in Jenkins:"
          - "   - Go to Jenkins > Manage Jenkins > Configure System"
          - "   - Add SonarQube server with URL: http://sonarqube.jenkins.svc.cluster.local:9000"
          - "   - Add the token as a credential"
